# version: '3'
# services:
#   webserver:
#     build: node
#     image: node-express-dev:1.0
#     tty: true
#     volumes:
#       - ./node/app:/app
#     ports:
#       - "8080:3000"

version: '3.8'
services:
  app:
    build: vue
    container_name: vue-project
    ports:
      - '8080:8080'
    volumes:
      - ./vue/src:/src
    stdin_open: true
    tty: true